services:
  - type: web
    name: n8n-cloud
    env: docker
    plan: free
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: GENERIC_TIMEZONE
        value: "Africa/Porto-Novo"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: "sqlite"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: WEBHOOK_URL
        value: https://n8n-cloud.onrender.com"
